### ISSUE TITLE
Get HTTPS!!

### ISSUE THREAD

**Issue by wolftune** [nardo/Equal.Vote#31]
the lack of https is bad technically and looks bad (I actually just got an email from someone who brought this up themselves) to anyone who looks for signals like that about whether a site is trustworthy and professional quality etc.

Get certs and make the site https ASAP

**Comment by nardo** [comment]
NationBuilder is rolling this out automatically and plans to have all sites
have it by Feb. 1.

**Comment by vorlonofportland** [comment]
appears to be resolved.
