### ISSUE TITLE
sentence critique

### ISSUE THREAD

**Issue by wolftune** [nardo/Equal.Vote#7]
> Because it uses both preference order and a notion of how much the voter approves of each candidate, SRV is both easier to tabulate and results in a more representative outcome than Instant Runoff Voting, another Ranked Choice system currently being considered for adoption in Oregon.

That's a really long sentence. It could be broken up easily and improved. A suggested alternative:

> SRV uses both preference order and a score of each candidate. Candidates may be scored equally when voters have no preference between two options. Compared with Instant Runoff Voting (another Ranked Choice system currently being considered for adoption in Oregon), SRV elections are easier to tabulate and give results that better represent voters' wishes.

**Comment by nardo** [comment]
Let's see if we can make a paragraph that is clearer and also uses fewer words. We have too many words as it is :-).

**Comment by SaraWolf** [comment]
It would help to know where exactly on the site this sentence came from. I can't seem to find it. Should we list the tab/folder/source at the beginning of the sentence critique or is there a system for this I don't know about? Without context here's an editing attempt. 

(Optional first sentence: SRV ranks candidates by preference and also rates overall support for each candidate.)
SRV promotes honesty and it's easy to count and understand the results. By comparison, Instant Runoff Voting can encourage voters to strategically vote for the lesser of two-evils, and actually understanding who won and why can be extremely complicated.

**Comment by wolftune** [comment]
This may be outdated or will be in the future. Yes, we should describe the situation clearer in issues generally,

@SaraWolf I think we should stop saying "by comparison Instant Runoff…" and similar and switch to saying "by comparison the *old* form of Instant Runoff…" because SRV *is* an instant-runoff system, just a new and improved one.

Closing this issue though.
